### ISSUE TITLE
如何运行？

### ISSUE THREAD

**Issue by 1234dacheng** [Depth2World/NLOST#1]
你好，我想请问一下咱这个代码是用什么配置的机器运行的？我这边一直显示显存不够。我在一个计算平台上申请了并行执行，6卡。还是不能正确执行。方便解答一下嘛？

**Comment by Depth2World** [comment]
你好, 训练使用的工作站是8卡A100(80G).

**Comment by Depth2World** [comment]
你好，现在有pretrain模型可供使用。训练显存大约38-39G，推理显存22-23G。
